stages:
  prepare:
    cmd: python .\src\data\make_dataset.py
    deps:
    # - .\data\raw\air_data\*.csv
    - .\src\data\make_dataset.py
    outs:
    - .\data\processed\data.csv
  preprocess:
    cmd: python .\src\data\preprocess.py
    deps:
    - .\data\processed\data.csv
    - .\src\data\preprocess.py
    outs:
    - .\data\interim\data.csv
